### ISSUE TITLE
Repeated :CrSearch getting confused

### ISSUE THREAD

**Issue by sgraham** [chromium/vim-codesearch#2]
Not sure if this is my config somehow, but here's the problem I'm having...

I open up a .cc under src (content/browser/loader/navigation_url_loader_network_service.cc for example)
:pwd is c:\src\cr\src
:CrSearch foo
works fine, opens a buffer with the results, but now :pwd is c:\src\cr
Ctrl-O back to the .cc, then :CrSearch foobar

"Codesearch: foobar"  1534 lines --0%--
Error detected while processing function crcs#CodeSearch:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\src\Dropbox\utils\vim-codesearch/vimsupport.py", line 60, in inner_call_wrapper
    vim.command('echoerr "{}"'.format(str(e.message).replace('"', '\\"')))
vim.error: Vim(echoerr):Vim(file):E325: ATTENTION

As long as I ":cd src" before I run :CrSearch foobar, things work.

**Comment by asankah** [comment]
Could you check if 03faae1650e300f40a6d068e0b4bb3a28dda2856 resolves this?

`:CrSearch bar` exposed another problem ( E.g. https://github.com/chromium/codesearch-py/issues/2 ). That should also be addressed in ToT.

**Comment by sgraham** [comment]
ToT makes multiple :CrSearch work, thanks! I still see :pwd getting modified though, which breaks my tags setup. Is it possible to avoid that?

**Comment by asankah** [comment]
Done in 00069cd0beb3c866b3d1967b7d5887f60e9dde61.

I was using `lcd` in a prior incantation of the plugin. But now it uses full paths for everything, so the `lcd` isn't necessary.

**Comment by sgraham** [comment]
Thanks! Works for me.
